<?php

namespace Proxies\__CG__\MagasinBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Magasin extends \MagasinBundle\Entity\Magasin implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'idMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'numRC', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'nomMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'cinProprietaireMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'nbProduit', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'adresseMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'villeMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'codePostaleMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'photoMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'bestSellerMagasin'];
        }

        return ['__isInitialized__', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'idMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'numRC', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'nomMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'cinProprietaireMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'nbProduit', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'adresseMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'villeMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'codePostaleMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'photoMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Magasin' . "\0" . 'bestSellerMagasin'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Magasin $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdMagasin()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdMagasin();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMagasin', []);

        return parent::getIdMagasin();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMagasin($idMagasin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMagasin', [$idMagasin]);

        return parent::setIdMagasin($idMagasin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumRC()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumRC', []);

        return parent::getNumRC();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumRC($numRC)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumRC', [$numRC]);

        return parent::setNumRC($numRC);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomMagasin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomMagasin', []);

        return parent::getNomMagasin();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomMagasin($nomMagasin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomMagasin', [$nomMagasin]);

        return parent::setNomMagasin($nomMagasin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCinProprietaireMagasin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCinProprietaireMagasin', []);

        return parent::getCinProprietaireMagasin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCinProprietaireMagasin($cinProprietaireMagasin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCinProprietaireMagasin', [$cinProprietaireMagasin]);

        return parent::setCinProprietaireMagasin($cinProprietaireMagasin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbProduit', []);

        return parent::getNbProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbProduit($nbProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbProduit', [$nbProduit]);

        return parent::setNbProduit($nbProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresseMagasin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresseMagasin', []);

        return parent::getAdresseMagasin();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresseMagasin($adresseMagasin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresseMagasin', [$adresseMagasin]);

        return parent::setAdresseMagasin($adresseMagasin);
    }

    /**
     * {@inheritDoc}
     */
    public function getVilleMagasin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVilleMagasin', []);

        return parent::getVilleMagasin();
    }

    /**
     * {@inheritDoc}
     */
    public function setVilleMagasin($villeMagasin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVilleMagasin', [$villeMagasin]);

        return parent::setVilleMagasin($villeMagasin);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodePostaleMagasin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodePostaleMagasin', []);

        return parent::getCodePostaleMagasin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodePostaleMagasin($codePostaleMagasin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodePostaleMagasin', [$codePostaleMagasin]);

        return parent::setCodePostaleMagasin($codePostaleMagasin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoMagasin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoMagasin', []);

        return parent::getPhotoMagasin();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoMagasin($photoMagasin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoMagasin', [$photoMagasin]);

        return parent::setPhotoMagasin($photoMagasin);
    }

    /**
     * {@inheritDoc}
     */
    public function getBestSellerMagasin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBestSellerMagasin', []);

        return parent::getBestSellerMagasin();
    }

    /**
     * {@inheritDoc}
     */
    public function setBestSellerMagasin($bestSellerMagasin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBestSellerMagasin', [$bestSellerMagasin]);

        return parent::setBestSellerMagasin($bestSellerMagasin);
    }

}
