<?php

namespace Proxies\__CG__\MagasinBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Produit extends \MagasinBundle\Entity\Produit implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'idProduit', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'libelle', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'quantite', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'photoProduit', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'marque', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'type', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'idMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'nbFoisVendu', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'description', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'prix'];
        }

        return ['__isInitialized__', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'idProduit', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'libelle', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'quantite', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'photoProduit', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'marque', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'type', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'idMagasin', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'nbFoisVendu', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'description', '' . "\0" . 'MagasinBundle\\Entity\\Produit' . "\0" . 'prix'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Produit $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdProduit()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getIdProduit();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdProduit', []);

        return parent::getIdProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdProduit($idProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdProduit', [$idProduit]);

        return parent::setIdProduit($idProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getLibelle()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLibelle', []);

        return parent::getLibelle();
    }

    /**
     * {@inheritDoc}
     */
    public function setLibelle($libelle)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLibelle', [$libelle]);

        return parent::setLibelle($libelle);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotoProduit()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotoProduit', []);

        return parent::getPhotoProduit();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotoProduit($photoProduit)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotoProduit', [$photoProduit]);

        return parent::setPhotoProduit($photoProduit);
    }

    /**
     * {@inheritDoc}
     */
    public function getMarque()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMarque', []);

        return parent::getMarque();
    }

    /**
     * {@inheritDoc}
     */
    public function setMarque($marque)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMarque', [$marque]);

        return parent::setMarque($marque);
    }

    /**
     * {@inheritDoc}
     */
    public function getType()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType($type)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$type]);

        return parent::setType($type);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrix()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrix', []);

        return parent::getPrix();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrix($prix)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrix', [$prix]);

        return parent::setPrix($prix);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdMagasin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdMagasin', []);

        return parent::getIdMagasin();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdMagasin($idMagasin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdMagasin', [$idMagasin]);

        return parent::setIdMagasin($idMagasin);
    }

    /**
     * {@inheritDoc}
     */
    public function getNbFoisVendu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNbFoisVendu', []);

        return parent::getNbFoisVendu();
    }

    /**
     * {@inheritDoc}
     */
    public function setNbFoisVendu($nbFoisVendu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNbFoisVendu', [$nbFoisVendu]);

        return parent::setNbFoisVendu($nbFoisVendu);
    }

    /**
     * {@inheritDoc}
     */
    public function getQuantite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getQuantite', []);

        return parent::getQuantite();
    }

    /**
     * {@inheritDoc}
     */
    public function setQuantite($quantite)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setQuantite', [$quantite]);

        return parent::setQuantite($quantite);
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription($description)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

}
