<?php

namespace Proxies\__CG__\RefugeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Refuge extends \RefugeBundle\Entity\Refuge implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'immatriculation', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'cin', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'nomrefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'emailrefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'telephonerefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'faxrefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'adresserefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'codepostalerefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'gouvernementrefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'photorefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'chat', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'chien', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'rongeur', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'autre'];
        }

        return ['__isInitialized__', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'immatriculation', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'cin', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'nomrefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'emailrefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'telephonerefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'faxrefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'adresserefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'codepostalerefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'gouvernementrefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'photorefuge', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'chat', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'chien', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'rongeur', '' . "\0" . 'RefugeBundle\\Entity\\Refuge' . "\0" . 'autre'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Refuge $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getImmatriculation()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getImmatriculation();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImmatriculation', []);

        return parent::getImmatriculation();
    }

    /**
     * {@inheritDoc}
     */
    public function setImmatriculation($immatriculation)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImmatriculation', [$immatriculation]);

        return parent::setImmatriculation($immatriculation);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomrefuge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomrefuge', []);

        return parent::getNomrefuge();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomrefuge($nomrefuge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomrefuge', [$nomrefuge]);

        return parent::setNomrefuge($nomrefuge);
    }

    /**
     * {@inheritDoc}
     */
    public function getEmailrefuge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEmailrefuge', []);

        return parent::getEmailrefuge();
    }

    /**
     * {@inheritDoc}
     */
    public function setEmailrefuge($emailrefuge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEmailrefuge', [$emailrefuge]);

        return parent::setEmailrefuge($emailrefuge);
    }

    /**
     * {@inheritDoc}
     */
    public function getTelephonerefuge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTelephonerefuge', []);

        return parent::getTelephonerefuge();
    }

    /**
     * {@inheritDoc}
     */
    public function setTelephonerefuge($telephonerefuge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTelephonerefuge', [$telephonerefuge]);

        return parent::setTelephonerefuge($telephonerefuge);
    }

    /**
     * {@inheritDoc}
     */
    public function getFaxrefuge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFaxrefuge', []);

        return parent::getFaxrefuge();
    }

    /**
     * {@inheritDoc}
     */
    public function setFaxrefuge($faxrefuge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFaxrefuge', [$faxrefuge]);

        return parent::setFaxrefuge($faxrefuge);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresserefuge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresserefuge', []);

        return parent::getAdresserefuge();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresserefuge($adresserefuge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresserefuge', [$adresserefuge]);

        return parent::setAdresserefuge($adresserefuge);
    }

    /**
     * {@inheritDoc}
     */
    public function getCodepostalerefuge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCodepostalerefuge', []);

        return parent::getCodepostalerefuge();
    }

    /**
     * {@inheritDoc}
     */
    public function setCodepostalerefuge($codepostalerefuge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCodepostalerefuge', [$codepostalerefuge]);

        return parent::setCodepostalerefuge($codepostalerefuge);
    }

    /**
     * {@inheritDoc}
     */
    public function getGouvernementrefuge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getGouvernementrefuge', []);

        return parent::getGouvernementrefuge();
    }

    /**
     * {@inheritDoc}
     */
    public function setGouvernementrefuge($gouvernementrefuge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setGouvernementrefuge', [$gouvernementrefuge]);

        return parent::setGouvernementrefuge($gouvernementrefuge);
    }

    /**
     * {@inheritDoc}
     */
    public function getChat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChat', []);

        return parent::getChat();
    }

    /**
     * {@inheritDoc}
     */
    public function setChat($chat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChat', [$chat]);

        return parent::setChat($chat);
    }

    /**
     * {@inheritDoc}
     */
    public function getChien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChien', []);

        return parent::getChien();
    }

    /**
     * {@inheritDoc}
     */
    public function setChien($chien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChien', [$chien]);

        return parent::setChien($chien);
    }

    /**
     * {@inheritDoc}
     */
    public function getRongeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRongeur', []);

        return parent::getRongeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setRongeur($rongeur)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRongeur', [$rongeur]);

        return parent::setRongeur($rongeur);
    }

    /**
     * {@inheritDoc}
     */
    public function getAutre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAutre', []);

        return parent::getAutre();
    }

    /**
     * {@inheritDoc}
     */
    public function setAutre($autre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAutre', [$autre]);

        return parent::setAutre($autre);
    }

    /**
     * {@inheritDoc}
     */
    public function getCin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCin', []);

        return parent::getCin();
    }

    /**
     * {@inheritDoc}
     */
    public function setCin($cin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCin', [$cin]);

        return parent::setCin($cin);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhotorefuge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhotorefuge', []);

        return parent::getPhotorefuge();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhotorefuge($photorefuge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhotorefuge', [$photorefuge]);

        return parent::setPhotorefuge($photorefuge);
    }

}
