<?php

namespace Proxies\__CG__\RefugeBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class QuestionnaireChien extends \RefugeBundle\Entity\QuestionnaireChien implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'id', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'tolererChien', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'tolererChat', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'affectueux', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'intelligent', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'chutePoils', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'calme', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'race'];
        }

        return ['__isInitialized__', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'id', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'tolererChien', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'tolererChat', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'affectueux', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'intelligent', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'chutePoils', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'calme', '' . "\0" . 'RefugeBundle\\Entity\\QuestionnaireChien' . "\0" . 'race'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (QuestionnaireChien $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCalme()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCalme', []);

        return parent::getCalme();
    }

    /**
     * {@inheritDoc}
     */
    public function setCalme($calme)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCalme', [$calme]);

        return parent::setCalme($calme);
    }

    /**
     * {@inheritDoc}
     */
    public function getRace()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRace', []);

        return parent::getRace();
    }

    /**
     * {@inheritDoc}
     */
    public function setRace($race)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRace', [$race]);

        return parent::setRace($race);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setTolererChien($tolererChien)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTolererChien', [$tolererChien]);

        return parent::setTolererChien($tolererChien);
    }

    /**
     * {@inheritDoc}
     */
    public function getTolererChien()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTolererChien', []);

        return parent::getTolererChien();
    }

    /**
     * {@inheritDoc}
     */
    public function setTolererChat($tolererChat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTolererChat', [$tolererChat]);

        return parent::setTolererChat($tolererChat);
    }

    /**
     * {@inheritDoc}
     */
    public function getTolererChat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTolererChat', []);

        return parent::getTolererChat();
    }

    /**
     * {@inheritDoc}
     */
    public function setAffectueux($affectueux)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAffectueux', [$affectueux]);

        return parent::setAffectueux($affectueux);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffectueux()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffectueux', []);

        return parent::getAffectueux();
    }

    /**
     * {@inheritDoc}
     */
    public function setIntelligent($intelligent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIntelligent', [$intelligent]);

        return parent::setIntelligent($intelligent);
    }

    /**
     * {@inheritDoc}
     */
    public function getIntelligent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIntelligent', []);

        return parent::getIntelligent();
    }

    /**
     * {@inheritDoc}
     */
    public function setChutePoils($chutePoils)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChutePoils', [$chutePoils]);

        return parent::setChutePoils($chutePoils);
    }

    /**
     * {@inheritDoc}
     */
    public function getChutePoils()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChutePoils', []);

        return parent::getChutePoils();
    }

}
